### ISSUE TITLE
got blue screened please help

### ISSUE THREAD

**Issue by Snapple220** [pblop/twitch-chat#14]
I ran the mod, got everything set up. it was working amazingly and I absolutely love it but just one thing. after, I added the mod (and the mod menu) I added the other mods I normally play with, and once it loaded my whole computer crashed and had to restart. I want to know what mod crashed this or if it can be fixed so that I can use my other mods

**Comment by PabloPerezRodriguez** [comment]
You need to give me the crash logs

**Comment by Gaming32** [comment]
> I ran the mod, got everything set up. it was working amazingly and I absolutely love it but just one thing. after, I added the mod (and the mod menu) I added the other mods I normally play with, and once it loaded my whole computer crashed and had to restart. I want to know what mod crashed this or if it can be fixed so that I can use my other mods

This most likely has nothing to do with the mod or Minecraft. If you try again, I am 95% sure that this will not happen if you try again.

**Comment by pblop** [comment]
That's my guess as well, and because they haven't said anything since, I'm closing this.
