### ISSUE TITLE
An option to add a prefix to Twitch chat when not broadcasting to the server

### ISSUE THREAD

**Issue by CarbonGhost** [pblop/twitch-chat#17]
I would like this as an option to work with the AdvancedChat mod's filters.

**Comment by PabloPerezRodriguez** [comment]
If I understand correctly, this already exists. You can choose a prefix to send messages to Twitch chat and another for the messages you receive from Twitch Chat.

**Comment by pblop** [comment]
Almost a year, no response, closing.
