### ISSUE TITLE
Russian language support

### ISSUE THREAD

**Issue by Zephyriumtdw** [pblop/twitch-chat#31]
I've translated mod on russian a
nd tried to pull it... Probably i'm not smart enough to work with github. So i leave it here.
**ru_ru.json**
[ru_ru.zip](https://github.com/pblop/twitch-chat/files/8372643/ru_ru.zip)

**Comment by pblop** [comment]
Hey, thanks! I'll add it to the next release!Hey, thanks! I'll add it to the next release!
