### ISSUE TITLE
[Issue] The mod doesnt work on 1.19.2, or at least the newest fabric version

### ISSUE THREAD

**Issue by stw222** [pblop/twitch-chat#36]
Crash report:
[https://paste.ee/p/75kT0](https://paste.ee/p/75kT0)
Minecraft 1.19.2
Twitch Chat Bridge 0.13.0b from modrinth
Fabric API 0.58.6+1.19.2
Fabric Loader 0.14.9
Mod Menu 4.0.6

Other Mods used to try and help find the problem (i had other mods installed besides these, but removed them to find the problem):
Mixin Conflict Helper 1.1.0
MixinTrace 1.1.1+1.17 (It still works on 1.19)
Not Enough Crashes 4.1.6+1.19
Spark 1.9.26

**Comment by HyperSoop** [comment]
same

**Comment by JW-JWGT** [comment]
yeah, i would like to see this fixed soon
