### ISSUE TITLE
OPTION configure not showing in mod's menu

### ISSUE THREAD

**Issue by AX09** [pblop/twitch-chat#41]
It did't show the configure button in the mod menu. Can someone help?

**Comment by natsimhan** [comment]
Same thing for me, no configuration button for this mod : 

- Minecraft 1.19.3
- Fabric API 0.73.0+1.19.3
- Mod Menu 5.0.2
- Twitch Chat Bridge 0.14.1b

[twitch_chat.error.log](https://github.com/pblop/twitch-chat/files/10496918/twitch_chat.error.log)
![Screenshot twitch-chat config with no button](https://user-images.githubusercontent.com/5631475/214500560-d69d366e-d5a6-46dc-a98c-6c5283433fc8.png)
![Screenshot menumod with button ^^](https://user-images.githubusercontent.com/5631475/214500564-4c528142-bd21-4e70-b2da-5fe7cf32b689.png)

**Comment by pblop** [comment]
Are you both using Minecraft 1.19.3?

**Comment by pblop** [comment]
Could you check if this version works for you?
[twitchchat-0.14.2b.jar.zip](https://github.com/pblop/twitch-chat/files/10498434/twitchchat-0.14.2b.jar.zip)

**Comment by pblop** [comment]
Great! I'll release this version as a fix.
I hope it works well in your livestream!
