### ISSUE TITLE
Version requirement on Modrinth is not correct

### ISSUE THREAD

**Issue by sarunint** [pblop/twitch-chat#46]
On https://modrinth.com/mod/twitch-chat/version/0.14.4b, it is marked that v0.14.4b is compatible with Minecraft 1.19 to 1.19.4, while in fact, this version only supports Minecraft 1.19.4.

**Comment by pblop** [comment]
I thought I had fixed that. Done

**Comment by sarunint** [comment]
Whoa, that was quick! Thanks!
